config/routes.rb
Shoppit::Application.routes.draw do
  devise_for :users

  resources :items

  resources :items, :only => [:show, :edit] do
    resources :votes, :only => [:create, :destroy]
    resources :comments
  end

  resources :comments, :only => [:index]

  root :to => 'items#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :dialogue

  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :cost, :description, :name, :url, :image

  validates_presence_of :name, :cost, :url

  has_many :comments
  belongs_to :user
  has_many :votes
  has_many :users, :through => :votes

  has_attached_file :image,
    :styles => { :medium  => "300x300>",
                 :thumb   => "100x100>" },
    :default_url => "/assets/missing.png"

  attr_accessor :image_file_name
  attr_accessor :image_content_type
  attr_accessor :image_file_size
  attr_accessor :image_updated_at

  def tally_votes
    count = 0

    votes.each do |vote|
      if vote.is_vote_up?
        puts 1
        count += 1
      else
        puts -1
        count -= 1
      end
    end

    count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :items
  has_many :comments
  has_many :votes
  has_many :voted_items, :through => :votes, :source => 'item'

  def has_voted?(item)
    voted_items.include?(item)
  end

  def vote_from(item)
    votes.where(:item_id => item.id).first
  end

  def is_vote_up?(item)
    vote_from(item).is_vote_up
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :is_vote_up, :item_id, :user_id

  belongs_to :user
  belongs_to :item

  def is_vote_up?
    is_vote_up
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ItemsController
  before_filter :authenticate_user!, :only => [:create]
  before_filter :find_item, :only => [:create]

  def index
    @comments = Comment.all
  end

  def create
    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    @comment.item = @item

    if @comment.save
      # Email disabled for now since the password won't work
      # ItemsMailer.item_notification(current_user, @item).deliver
      # redirect_to @item, :notice => "Comment created!"
      
      # The actual response to a successful save can be found in /views/comments/create.js.erb
    else
      redirect_to @item, :notice => "There was an error"
    end
  end

  def destroy
    @comment = current_user.comment
    if @comment.destroy
      redirect_to item_path(@comment.item)
    else
      redirect_to item_path(@comment.item), :notice => "There was a problem :("
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :find_item, :only => [:show]
  before_filter :find_authenticated_item, :only => [:edit, :update, :destroy]

  def index
    @items = Item.all.reverse
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(params[:item])
    @item.user = current_user
    if @item.save
      redirect_to item_path(@item), :notice => "Item created!"
    else
      redirect_to @item, :alert => "Something went wrong..."
    end
  end

  def show
    # Get the current item's comments
    @all_comments = @item.comments

    # Prepare an empty comment
    @comment = Comment.new

    # Prepare an empty vote
    # @vote = current_user.vote_from(@item)
    @vote = (current_user && current_user.vote_from(@item)) || Vote.new
  end

  def edit
  end

  def update
    if @item.update_attributes(params[:item])
      redirect_to item_path(@item), :notice => "Item Modified!"
    else
      render :edit, :alert => "Something went wrong..."
    end
  end

  def destroy
    if @item.destroy
      redirect_to items_path
    else
      render :nothing => true
    end
  end

  private

  def find_item
    @item = Item.find(params[:item_id] || params[:id])
  end

  def find_authenticated_item
    @item = current_user.items.find(params[:item_id] || params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ItemsController
  before_filter :find_item
  before_filter :find_authenticated_item, :except => [:create, :destroy]

  def create
    @vote = Vote.new
    @vote.user = current_user
    @vote.item = @item
    @vote.is_vote_up = params[:is_vote_up] || true

    if !current_user.has_voted?(@item) && @vote.save
      redirect_to @item, :notice => 'Vote added'
    else
      redirect_to @item, :alert => 'You already voted!'
    end
  end

  def destroy
    @vote = Vote.find(params[:id])
    if @vote.destroy
      redirect_to @item, :notice => "Vote removed"
    else
      redirect_to @item, :alert => "Something went wrong!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_date(date)
    date.strftime('%d %b %Y')
  end

  def dollar_random(min, max)
    (rand * (100-1) + 1).round(0) + 0.95
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<article class="comment">
  <%= comment.dialogue %>
  <footer>
    <span class="author">
      <%= puts comment.user %>
    </span>
    <!--%= link_to "Edit", edit_item_comment_path(item_id: comment.item, id: comment) %-->
    <!-- %= link_to "Delete", item_comment_path(comment.item, comment), :method => :delete, :confirm => "Are you sure?" %-->
  </footer>
</article>

app/views/comments/_comment_collection.html.erb
<div class="comments-collection">
  <% if comments.empty? %>
    <div class="muted">
      There are currently no comments!
    </div>
  <% else %>
    <% comments.each do |c| %>
      <%= render 'comments/comment', :comment => c %>
    <% end %>
  <% end %>
</div>

app/views/comments/_new_comment_form.html.erb
<% if current_user %>
    <%= form_for @comment, :remote => true, :url => item_comments_path(@item) do |f| %>
      <%= f.text_area :dialogue, :rows => 5 %>
      <br />
      <%= f.submit 'Post Your Thoughts', :class => 'btn' %>
    <% end %>
<% end %>

app/views/comments/create.js.erb
$('.comments-collection').append("<%= j render @comment  %>");

app/views/comments/index.html.erb
<h1>Comments</h1>

<% @comments.each do |c| %>
  <article class="app-comment">
    <%= c.dialogue %>
  </article>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment!</h1>

<%= form_for @comment do |f| %>

  <%= f.label :dialogue %>

  <%= f.text_area :dialogue %>

  <br />

  <%= f.submit 'Add to Discussion', :class => 'btn' %>
<% end %>

app/views/items/_comments.html.erb
<aside class="app-comments row">
  <h2 class="span12">Discussion</h2>

  <div class="span12">
    <%= render 'comments/new_comment_form' %>
  </div>
    
  <div class="span12">
    <%= render 'comments/comment_collection', :comments => @all_comments %>
  </div>

</aside>

app/views/items/_item-rank.html.erb
<div class="app-rank-arrows">
  <a class="rank-btn rank-btn--up">
    <i class="icon-chevron-up"></i>
  </a>

  <span class="rank-count">
    123
  </span>

  <a class="rank-btn rank-btn--down">
    <i class="icon-chevron-down"></i>
  </a>
</div>

app/views/items/_item.html.erb
<article class="app-item span12">
  <div class="row">
    <%= render "item_rank", :item => item, :vote => item.votes %>

    <figure class="span2 item-graphic">
      <a href='<%= "#{item.url}" %>'>
        <%= image_tag item.image.url, :class => 'item-thumb' %>
        <!--%= image_tag 'missing.png' %-->
        <!--span style="display: block; width: 100px; height: 100px; margin: 0 10px; background: white; border: 1px solid #eee; box-shadow: inset 0 0 10px rgba(0, 0, 0, 0.05)"></span-->
      </a>
        
      <% if item.cost %>
        <figcaption class="item-banner">
          <%= number_to_currency(item.cost) %>
        </figcaption>
      <% end %>
    </figure>
    
    <div class="span9">
      <header class="item-header">
        <h2 class="item-heading">
          <%= link_to item.name, item.url %>
        </h2>
      </header>
      
      <div class="item-body">
        <%= item.description %>
      </div>

      <footer class="item-footer">
        <% if item.comments.count > 1 %>
          <%= link_to "#{item.comments.count} Comments", item,
            :class => 'item-discussionCount' %>
        <% elsif item.comments.count == 1 %>
          <%= link_to "#{item.comments.count} Comment", item,
            :class => 'item-discussionCount' %>
        <% else %>
          <%= link_to "Start a Discussion", item,
            :class => 'item-discussionCount' %>
        <% end %>
        
        <span class="item-createdDate">
          <%= format_date(item.created_at) %>
        </span>
      </footer>
    </div>
  </div>
</article>

app/views/items/_item_collection.html.erb
<% @items.each do |item| %>
  <%= render 'item', :item => item %>
<% end %>

app/views/items/_item_rank.html.erb
<div class="app-rank-arrows span1">
  
  <% if current_user && current_user.has_voted?(item) && current_user.is_vote_up?(item) %>
    <%= link_to '<i class="icon-chevron-up"></i>'.html_safe,
      item_vote_path(item, vote),
      :method => 'DELETE',
      :class => 'rank-btn rank-btn--voted' %>
  <% else %>
    <%= link_to '<i class="icon-chevron-up"></i>'.html_safe,
      item_votes_path(item),
      :method => 'POST',
      :class => 'rank-btn' %>
  <% end %>

  <span class="rank-count">
    <%= item.tally_votes %>
  </span>
  
  <% if current_user && current_user.has_voted?(item) && !current_user.is_vote_up?(item) %>
    <%= link_to '<i class="icon-chevron-down"></i>'.html_safe,
      item_vote_path(item, vote),
      :method => 'DELETE',
      :class => 'rank-btn rank-btn--voted' %>
  <% else %>
    <%= link_to '<i class="icon-chevron-down"></i>'.html_safe,
      item_votes_path(:item_id => item.id, :is_vote_up => :false),
      :method => 'POST',
      :class => 'rank-btn' %>
  <% end %>
</div>

app/views/items/_temp.html.erb
<!-- Use this for a User Profile page or something... -->

<% current_user.items.each do |item| %>
  <article>
    <%= link_to item.name, item %>
  </article>
<% end %>

app/views/items/edit.html.erb
<h1>New Item!</h1>

<%= form_for @item do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <br />

    <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<div class="app-items row">
  <%= render 'item_collection', :items => @items %>
</div>

app/views/items/new.html.erb
<h1>New Item!</h1>

<%= form_for @item, :html => { :multipart => true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <div class="row">
    <div class="span3">
      <%= f.label :cost %>
      <%= f.text_field :cost %>
    </div>
    <div class="span9">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
  </div>

  <%= f.file_field :image %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <br />

  <%= f.submit 'Share Item', :class => 'btn' %>
<% end %>

app/views/items/show.html.erb
<div class="app-items row">
  <%= render 'item', :item => @item %>
</div>

<%= render "comments" %>

app/views/layouts/_footer.html.erb
<footer class="appfoot">
  <div class="container">
    <p class="muted credit">A "Ruby On Rails, For Starters" Workshop Site by <a href="http://www.jeffkamo.com">Jeff Kamo</a> <%= image_tag 'rails.png' %></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="apphead navbar nav-fixed-top">  
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">Shoppit</a>

      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'nav-link' %>
        <%= link_to "Create New Item", new_item_path, :class => 'nav-link' %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, :class => 'nav-link' %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shoppit</title>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
</head>
<body>
  <div class="wrap">
    <%= render 'layouts/header' %>

    <% if notice || alert %>
      <div class="flash container">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-block"><%= alert %></p>
        <% end %>
      </div>
    <% end %>

    <section class="app container">
      <%= yield %>
    </section>

    <div class="push"></div>
  </div>
  
  <%= render 'layouts/footer' %>

</body>
</html>